s = list(map(str,input().split('\n')))
print(s)
# s.replace(" ","%20")
# s.replace("!","%21")
# s.replace("$","%24")
# s.replace("%","%25")
# s.replace("(","%28")
# s.replace(")","%29")
# s.replace("*",r"%2a")